# Generated by Django 4.2.3 on 2023-08-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helpermodel',
            name='availability_status_week',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1),
        ),
        migrations.AlterField(
            model_name='helpermodel',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadstatusnotificationmodel',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
