# Generated by Django 4.2.3 on 2023-07-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_leadmodel_country_alter_leadmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='contact_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('first_contact', 'First Contact'), ('follow_up', 'Follow Up'), ('failed', 'Field'), ('conformed', 'Conformed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='lead_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
