# Generated by Django 4.2.3 on 2023-07-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_leadmodel_lead_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadmodel',
            old_name='contact_status',
            new_name='lead_status',
        ),
    ]
