# Generated by Django 4.2.3 on 2023-07-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_contact_status_leadmodel_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperAdditionalDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HelperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('helper_status', models.CharField(choices=[('pending', 'Pending'), ('first_contact', 'First Contact'), ('follow_up', 'Follow Up'), ('failed', 'Failed'), ('conformed', 'Conformed')], default='pending', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('primary_phone', models.IntegerField()),
                ('secondary_phone', models.IntegerField(blank=True, null=True)),
                ('email_id', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal')], max_length=100)),
                ('country', models.CharField(choices=[('india', 'INDIA')], max_length=100)),
                ('additional_comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelperPreferredLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.helpermodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='leadpreferredlanguagemodel',
            name='lead',
        ),
        migrations.DeleteModel(
            name='LeadAdditionalDetailsModel',
        ),
        migrations.DeleteModel(
            name='LeadModel',
        ),
        migrations.DeleteModel(
            name='LeadPreferredLanguageModel',
        ),
        migrations.AddField(
            model_name='helperadditionaldetailsmodel',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.helpermodel'),
        ),
    ]
