# Generated by Django 4.2.3 on 2023-07-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_helperadditionaldetailsmodel_helpermodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelperAdditionalDetailsModel',
            new_name='HelperAdditionalSkillSetModel',
        ),
        migrations.RemoveField(
            model_name='helpermodel',
            name='helper_status',
        ),
        migrations.AddField(
            model_name='helpermodel',
            name='availability_status_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='helpermodel',
            name='work_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HelperSkillSetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.helpermodel')),
            ],
        ),
    ]
