# Generated by Django 4.2.3 on 2023-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_employee_name_helperhistorymodel_admin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperhistorymodel',
            name='history_status',
            field=models.CharField(choices=[('create', 'create'), ('delate', 'delete'), ('update', 'update')], default='create', max_length=100),
        ),
    ]
