# Generated by Django 4.2.3 on 2023-08-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_helperhistorymodel_history_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperhistorymodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='helperhistorymodel',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadstatusnotificationmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leadstatusnotificationmodel',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
