# Generated by Django 4.2.3 on 2023-07-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_helperadditionaldetailsmodel_helperadditionalskillsetmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpermodel',
            name='helper_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('first_contact', 'First Contact'), ('follow_up', 'Follow Up'), ('failed', 'Failed'), ('conformed', 'Conformed')], default='pending', max_length=50),
        ),
    ]
