# Generated by Django 4.2.3 on 2023-07-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_helpermodel_helper_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helperadditionalskillsetmodel',
            old_name='additional_details',
            new_name='additional_skill',
        ),
    ]
