# Generated by Django 4.2.3 on 2023-08-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_helperhistorymodel_create_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelperHistoryModel',
        ),
    ]
