# Generated by Django 4.2.3 on 2023-07-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_additional_details_helperadditionalskillsetmodel_additional_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpermodel',
            name='helper_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('pending', 'Pending'), ('need_to_contact', 'Need to contact')], default='pending', max_length=50),
        ),
    ]
