# Generated by Django 4.2.3 on 2023-08-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_helperhistorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='additional_comment',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='availability_status_week',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='helper_status',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='near_by',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='street',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='work_experience',
        ),
        migrations.RemoveField(
            model_name='helperhistorymodel',
            name='zipcode',
        ),
    ]
