# Generated by Django 4.2.3 on 2023-08-01 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_alter_helpermodel_helper_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpermodel',
            name='helper_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('pending', 'Pending'), ('need_to_contact', 'Need to contact')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
