# Generated by Django 4.2.3 on 2023-08-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_helperhistorymodel_additional_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperhistorymodel',
            name='helper_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
