# Generated by Django 4.2.3 on 2023-08-01 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_helpermodel_helper_status_employeemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatusNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('placed', 'Placed'), ('first contact', 'First contact'), ('follow up', 'Follow up'), ('failed', 'Failed'), ('confirmed', 'Confirmed')], max_length=50)),
                ('msg', models.CharField(max_length=400)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.helpermodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
