# Generated by Django 4.0.5 on 2023-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_helperhistorymodel_helper_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperhistorymodel',
            name='history_status',
            field=models.CharField(choices=[('create', 'create'), ('delete', 'delete'), ('update', 'update')], default='create', max_length=100),
        ),
    ]
