# Generated by Django 4.2.3 on 2023-08-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_leadstatusnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatusnotification',
            name='type',
            field=models.CharField(choices=[('pending', 'Pending'), ('first contact', 'First contact'), ('follow up', 'Follow up'), ('failed', 'Failed'), ('confirmed', 'Confirmed')], default='pending', max_length=50),
        ),
    ]
