# Generated by Django 4.0.5 on 2023-08-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_historymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.helperhistorymodel'),
        ),
    ]
