# Generated by Django 4.2.3 on 2023-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_leadstatusnotification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadLastRowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
