# Generated by Django 4.0.5 on 2023-08-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_historymodel_helper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryModel',
        ),
    ]
