# Generated by Django 4.2.3 on 2023-08-01 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_delete_leadlastrowmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatusNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('first contact', 'First contact'), ('follow up', 'Follow up'), ('failed', 'Failed'), ('confirmed', 'Confirmed')], default='pending', max_length=50)),
                ('msg', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
