# Generated by Django 4.2.3 on 2023-08-01 18:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_leadstatusnotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadStatusNotification',
            new_name='LeadStatusNotificationModel',
        ),
    ]
