# Generated by Django 4.0.5 on 2023-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_historymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='lead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
