# Generated by Django 4.2.3 on 2023-08-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_historymodel_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.helperhistorymodel'),
        ),
    ]
