# Generated by Django 4.2.3 on 2023-08-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_leadstatusnotification_leadstatusnotificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatusnotificationmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
