# Generated by Django 4.2.3 on 2023-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_leadstatusnotificationmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpermodel',
            name='locality',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='helpermodel',
            name='near_by',
            field=models.BooleanField(default=False),
        ),
    ]
