# Generated by Django 4.2.3 on 2023-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_helpermodel_locality_helpermodel_near_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpermodel',
            name='locality',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default=None, max_length=30, null=True),
        ),
    ]
