# Generated by Django 4.2.3 on 2023-08-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_helpermodel_id_pdf_helpermodel_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpermodel',
            name='phone_valid',
            field=models.BooleanField(default=False),
        ),
    ]
