# Generated by Django 4.2.3 on 2023-08-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_helpermodel_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpermodel',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='helpermodel',
            name='near_by',
        ),
    ]
