# Generated by Django 4.2.3 on 2023-08-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_helpermodel_availability_status_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpermodel',
            name='availability_status_week',
            field=models.CharField(max_length=400),
        ),
    ]
