# Generated by Django 4.2.3 on 2023-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_helpermodel_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpermodel',
            name='locality',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), (None, None)], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='helpermodel',
            name='near_by',
            field=models.BooleanField(default=False),
        ),
    ]
