# Generated by Django 4.2.3 on 2023-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_helpermodel_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpermodel',
            name='dob',
            field=models.DateField(default=1987),
            preserve_default=False,
        ),
    ]
