# Generated by Django 4.2.3 on 2023-08-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_helpermodel_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpermodel',
            name='dob',
        ),
    ]
