# Generated by Django 4.2.3 on 2023-08-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_helperjobrolemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpermodel',
            name='call_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not called', 'Not called')], default=None, max_length=100, null=True),
        ),
    ]
